### ISSUE TITLE
theme issue

### ISSUE THREAD

**Issue by Phntomm** [harbassan/spicetify-galaxy#75] opened 2024-05-08 07:08 UTC
So this is happening since like a day or two and i've been using this theme for some months and never faced any issue. 
![image_2024-05-08_120357810](https://github.com/harbassan/spicetify-galaxy/assets/169238070/55d9f6fe-058c-4b79-8b0b-ae9362a279d5)
this weird bar is showing everywhere and that weird color on every playlist.
btw spotify version 1.2.17 and spicetify version 2.36.4
![image_2024-05-08_120805970](https://github.com/harbassan/spicetify-galaxy/assets/169238070/088d30d3-be83-46dc-ab64-04f61ccbe21f)
as u can see the colors
![im22age](https://github.com/harbassan/spicetify-galaxy/assets/169238070/62a6cb60-c214-4d87-8889-1fcd2839b2ad)

(this is what it used to look like before)

**Comment by Freaky-Don36** [comment] 2024-05-08 10:22
Hey, I'm having the same issue too?

https://github.com/harbassan/spicetify-galaxy/assets/169249598/476bcaa4-dd2d-4129-8f09-084f160584fa

**Comment by Hrushal-Nikhare** [comment] 2024-05-09 13:22
hey @Phntomm the issue is with another extension you have installed which i suppose is called "Cover Ambience"

**Comment by Hrushal-Nikhare** [comment] 2024-05-09 13:23
and @Freaky-Don36 i have a temp fix for the issue you are facing in #73

**Comment by harbassan** [comment] 2024-05-09 13:28
should be fixed now, just give it some time to update in marketplace.

also, @Freaky-Don36 why you stalking me lol.

**Comment by Freaky-Don36** [comment] 2024-05-10 07:08
Thank you 🥰

**Closed** 2024-05-10 07:28 UTC
